### ISSUE TITLE
Single signon non valorizzato

### ISSUE THREAD

**Issue by RossiNIT** [italia/spid-aspnetcore#64]
Ho aggiornato la libreria all'ultima versione nella mia applicazione (derivata dal progetto di sample 1_SimpleSPWebApp.
Aggiungendo nella lista degli IdP gli IdP di test che solitamente uso, in alcuni di essi l'applicazione ritorna questo errore ancor prima di reindirizzare la chiamata all'IdP:

```
System.Exception: L'url del single signon deve essere valorizzato

   at SPID.AspNetCore.Authentication.Helpers.BusinessValidation.ValidationCondition(Func`1 condition, String error) in C:\Users\giacomo.rossi\tfs\NIT System SPID\SPID.AspNetCore.Authentication\Helpers\BusinessValidation.cs:line 17

   at SPID.AspNetCore.Authentication.Saml.SamlHandler.GetAuthnRequest(String requestId, String entityId, String assertionConsumerServiceURL, Nullable`1 assertionConsumerServiceIndex, UInt16 attributeConsumingServiceIndex, X509Certificate2 certificate, Int32 securityLevel, RequestMethod requestMethod, IdentityProvider identityProvider) in C:\Users\giacomo.rossi\tfs\NIT System SPID\SPID.AspNetCore.Authentication\Saml\SamlHandler.cs:line 60

   at SPID.AspNetCore.Authentication.SpidHandler.HandleChallengeAsync(AuthenticationProperties properties) in C:\Users\giacomo.rossi\tfs\NIT System SPID\SPID.AspNetCore.Authentication\SpidHandler.cs:line 111

   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.ChallengeAsync(AuthenticationProperties properties)

   at Microsoft.AspNetCore.Authentication.AuthenticationService.ChallengeAsync(HttpContext context, String scheme, AuthenticationProperties properties)

   at Microsoft.AspNetCore.Mvc.ChallengeResult.ExecuteResultAsync(ActionContext context)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()

--- End of stack trace from previous location ---

   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()

--- End of stack trace from previous location ---

   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)

   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)

   at SPID.AspNetCore.Authentication.Extensions.SpidSPMetadataMiddleware.Invoke(HttpContext context, IOptionsSnapshot`1 options, IServiceProvidersFactory serviceProvidersFactory) in C:\Users\giacomo.rossi\tfs\NIT System SPID\SPID.AspNetCore.Authentication\Extensions\SpidSPMetadataMiddleware.cs:line 36

   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)

   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)

   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)

   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)

   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

![image](https://github.com/italia/spid-aspnetcore/assets/118269033/a62082e4-0857-4a72-96ce-cebf57ca96dd)

I providers da me aggiunti sono i seguenti:

```
"Providers": [
            {
                "EntityId": "https://validator.spid.gov.it",
                "Name": "Validator",
                "OrganizationName": "Validator SPID",
                "OrganizationDisplayName": "Validator SPID",
                "X509SigningCertificate": "MIIEfzCCA2egAwIBAgIUVSeD58C3IyG/SwADsok3KChutAAwDQYJKoZIhvcNAQELBQAwgc4xCzAJBgNVBAYTAklUMQ0wCwYDVQQIDARSb21lMQ0wCwYDVQQHDARSb21lMS0wKwYDVQQKDCRBZ0lEIC0gQWdlbnppYSBwZXIgbCdJdGFsaWEgRGlnaXRhbGUxLDAqBgNVBAsMI0FnSUQgLSBTZXJ2aXppbyBhY2NyZWRpdGFtZW50byBTUElEMR4wHAYDVQQDDBV2YWxpZGF0b3Iuc3BpZC5nb3YuaXQxJDAiBgkqhkiG9w0BCQEWFXNwaWQudGVjaEBhZ2lkLmdvdi5pdDAeFw0yMTA5MjgwNzM5MTFaFw0yMzA5MjgwNzM5MTFaMIHOMQswCQYDVQQGEwJJVDENMAsGA1UECAwEUm9tZTENMAsGA1UEBwwEUm9tZTEtMCsGA1UECgwkQWdJRCAtIEFnZW56aWEgcGVyIGwnSXRhbGlhIERpZ2l0YWxlMSwwKgYDVQQLDCNBZ0lEIC0gU2Vydml6aW8gYWNjcmVkaXRhbWVudG8gU1BJRDEeMBwGA1UEAwwVdmFsaWRhdG9yLnNwaWQuZ292Lml0MSQwIgYJKoZIhvcNAQkBFhVzcGlkLnRlY2hAYWdpZC5nb3YuaXQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCjbuxHXdLPZZc/b9YaSqxdUsdDLYNdpBjdEmPoNf2LrXlBv8IODStRkNyQsAnOdy+R7Ud+kdtJi+tblx8e29RHRSsvl6HL3O0/3aS9XsyUGhbUE45SLxNWTMubU7UyS1mRhSdEUIbtVxYgSu1uH6zeIN2DhxQZIb0APZ7aLbJewu25qECz2dnV54R45pBwst/6MrnBa15VfKDRA2zdgfGjIgGWgxWtf7CqzfXnhush0IyaL4RVn/7tUurxj//LY6f37yMP1EAIbn9thc37ZhyfM9grAH3Cc4kdEB+HaiQ83fTH6LshPgTHww0w88TxK1jrV/vEG3T6ZhCqXt7qRvKtAgMBAAGjUzBRMB0GA1UdDgQWBBT0HytnpUbkZxLa0N+lfD08WrQX2TAfBgNVHSMEGDAWgBT0HytnpUbkZxLa0N+lfD08WrQX2TAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQCYcghyQ6zhRmLDzliNgJxPUOTJa/9UmZRgWYFcYHMumXTTTT/fmy00hTRFIKWpB0AibyEJhODIjCqNJN3RsCDbkwEDR0thhMQ51vK8oB9X1JVMDQ8v+eRTQTa8bZv8W8IPn7fgQFoX5IkiXEQtgf+hi/ErX/L4O6qbYxE/lIZneXXxlZUVM4YN9aS25nmuCumg9MbrmCCwplliKgKSZ77IERmcFm1tzpEFMJNI8LIaDL8VLSOosIMdLwel3oP3mosTw2hkSfyVUwHp/0y4rJ+zIel/4vBoySsyrJCCi8wBe9WNpIlUV/gGSayPkJMe0qc8m0GzncZDkqF/Bd7xsUHc",
                "OrganizationLogoUrl": "https://validator.spid.gov.it/img/idp-logo.png",
                "SingleSignOnServiceUrlPost": "https://validator.spid.gov.it/samlsso",
                "SingleSignOutServiceUrlPost": "https://validator.spid.gov.it/samlsso",
                "SingleSignOnServiceUrlRedirect": "https://validator.spid.gov.it/samlsso",
                "SingleSignOutServiceUrlRedirect": "https://validator.spid.gov.it/samlsso",
                "Type": "StagingProvider"
            },
            {
                "EntityId": "https://demo.spid.gov.it/validator",
                "Name": "SPID Validator",
                "OrganizationName": "Validator SPID",
                "OrganizationDisplayName": "SPID Validator",
                "X509SigningCertificate": "MIIEGDCCAwCgAwIBAgIJAOrYj9oLEJCwMA0GCSqGSIb3DQEBCwUAMGUxCzAJBgNVBAYTAklUMQ4wDAYDVQQIEwVJdGFseTENMAsGA1UEBxMEUm9tZTENMAsGA1UEChMEQWdJRDESMBAGA1UECxMJQWdJRCBURVNUMRQwEgYDVQQDEwthZ2lkLmdvdi5pdDAeFw0xOTA0MTExMDAyMDhaFw0yNTAzMDgxMDAyMDhaMGUxCzAJBgNVBAYTAklUMQ4wDAYDVQQIEwVJdGFseTENMAsGA1UEBxMEUm9tZTENMAsGA1UEChMEQWdJRDESMBAGA1UECxMJQWdJRCBURVNUMRQwEgYDVQQDEwthZ2lkLmdvdi5pdDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAK8kJVo+ugRrbbv9xhXCuVrqi4B7/MQzQc62ocwlFFujJNd4m1mXkUHFbgvwhRkQqo2DAmFeHiwCkJT3K1eeXIFhNFFroEzGPzONyekLpjNvmYIs1CFvirGOj0bkEiGaKEs+/umzGjxIhy5JQlqXE96y1+Izp2QhJimDK0/KNij8I1bzxseP0Ygc4SFveKS+7QO+PrLzWklEWGMs4DM5Zc3VRK7g4LWPWZhKdImC1rnS+/lEmHSvHisdVp/DJtbSrZwSYTRvTTz5IZDSq4kAzrDfpj16h7b3t3nFGc8UoY2Ro4tRZ3ahJ2r3b79yK6C5phY7CAANuW3gDdhVjiBNYs0CAwEAAaOByjCBxzAdBgNVHQ4EFgQU3/7kV2tbdFtphbSA4LH7+w8SkcwwgZcGA1UdIwSBjzCBjIAU3/7kV2tbdFtphbSA4LH7+w8SkcyhaaRnMGUxCzAJBgNVBAYTAklUMQ4wDAYDVQQIEwVJdGFseTENMAsGA1UEBxMEUm9tZTENMAsGA1UEChMEQWdJRDESMBAGA1UECxMJQWdJRCBURVNUMRQwEgYDVQQDEwthZ2lkLmdvdi5pdIIJAOrYj9oLEJCwMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAJNFqXg/V3aimJKUmUaqmQEEoSc3qvXFITvT5f5bKw9yk/NVhR6wndL+z/24h1OdRqs76blgH8k116qWNkkDtt0AlSjQOx5qvFYh1UviOjNdRI4WkYONSw+vuavcx+fB6O5JDHNmMhMySKTnmRqTkyhjrch7zaFIWUSV7hsBuxpqmrWDoLWdXbV3eFH3mINA5AoIY/m0bZtzZ7YNgiFWzxQgekpxd0vcTseMnCcXnsAlctdir0FoCZztxMuZjlBjwLTtM6Ry3/48LMM8Z+lw7NMciKLLTGQyU8XmKKSSOh0dGh5Lrlt5GxIIJkH81C0YimWebz8464QPL3RbLnTKg+c=",
                "OrganizationLogoUrl": "https://validator.spid.gov.it/img/idp-logo.png",
                "SingleSignOnServiceUrl": "https://demo.spid.gov.it/validator/samlsso",
                "SingleSignOutServiceUrl": "https://demo.spid.gov.it/validator/samlsso",
                "SingleSignOnServiceUrlRedirect": "https://demo.spid.gov.it/validator/samlsso",
                "SingleSignOutServiceUrlRedirect": "https://demo.spid.gov.it/validator/samlsso",
                "Type": "StagingProvider"
            },
            {
                "EntityId": "https://demo.spid.gov.it",
                "Name": "DemoSpid",
                "OrganizationName": "DemoSpid",
                "OrganizationDisplayName": "DemoSpid",
                "X509SigningCertificate": "MIIEGDCCAwCgAwIBAgIJAOrYj9oLEJCwMA0GCSqGSIb3DQEBCwUAMGUxCzAJBgNVBAYTAklUMQ4wDAYDVQQIEwVJdGFseTENMAsGA1UEBxMEUm9tZTENMAsGA1UEChMEQWdJRDESMBAGA1UECxMJQWdJRCBURVNUMRQwEgYDVQQDEwthZ2lkLmdvdi5pdDAeFw0xOTA0MTExMDAyMDhaFw0yNTAzMDgxMDAyMDhaMGUxCzAJBgNVBAYTAklUMQ4wDAYDVQQIEwVJdGFseTENMAsGA1UEBxMEUm9tZTENMAsGA1UEChMEQWdJRDESMBAGA1UECxMJQWdJRCBURVNUMRQwEgYDVQQDEwthZ2lkLmdvdi5pdDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAK8kJVo+ugRrbbv9xhXCuVrqi4B7/MQzQc62ocwlFFujJNd4m1mXkUHFbgvwhRkQqo2DAmFeHiwCkJT3K1eeXIFhNFFroEzGPzONyekLpjNvmYIs1CFvirGOj0bkEiGaKEs+/umzGjxIhy5JQlqXE96y1+Izp2QhJimDK0/KNij8I1bzxseP0Ygc4SFveKS+7QO+PrLzWklEWGMs4DM5Zc3VRK7g4LWPWZhKdImC1rnS+/lEmHSvHisdVp/DJtbSrZwSYTRvTTz5IZDSq4kAzrDfpj16h7b3t3nFGc8UoY2Ro4tRZ3ahJ2r3b79yK6C5phY7CAANuW3gDdhVjiBNYs0CAwEAAaOByjCBxzAdBgNVHQ4EFgQU3/7kV2tbdFtphbSA4LH7+w8SkcwwgZcGA1UdIwSBjzCBjIAU3/7kV2tbdFtphbSA4LH7+w8SkcyhaaRnMGUxCzAJBgNVBAYTAklUMQ4wDAYDVQQIEwVJdGFseTENMAsGA1UEBxMEUm9tZTENMAsGA1UEChMEQWdJRDESMBAGA1UECxMJQWdJRCBURVNUMRQwEgYDVQQDEwthZ2lkLmdvdi5pdIIJAOrYj9oLEJCwMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAJNFqXg/V3aimJKUmUaqmQEEoSc3qvXFITvT5f5bKw9yk/NVhR6wndL+z/24h1OdRqs76blgH8k116qWNkkDtt0AlSjQOx5qvFYh1UviOjNdRI4WkYONSw+vuavcx+fB6O5JDHNmMhMySKTnmRqTkyhjrch7zaFIWUSV7hsBuxpqmrWDoLWdXbV3eFH3mINA5AoIY/m0bZtzZ7YNgiFWzxQgekpxd0vcTseMnCcXnsAlctdir0FoCZztxMuZjlBjwLTtM6Ry3/48LMM8Z+lw7NMciKLLTGQyU8XmKKSSOh0dGh5Lrlt5GxIIJkH81C0YimWebz8464QPL3RbLnTKg+c=",
                "OrganizationLogoUrl": "https://validator.spid.gov.it/img/idp-logo.png",
                "SingleSignOnServiceUrl": "https://demo.spid.gov.it/samlsso",
                "SingleSignOutServiceUrl": "https://demo.spid.gov.it/samlsso",
                "SingleSignOnServiceUrlRedirect": "https://demo.spid.gov.it/samlsso",
                "SingleSignOutServiceUrlRedirect": "https://demo.spid.gov.it/samlsso",
                "Type": "StagingProvider"
            },
            {
                "EntityId": "https://localhost:8443",
                "Name": "SpidSpTest",
                "OrganizationName": "SpidSpTest",
                "OrganizationDisplayName": "SpidSpTest",
                "X509SigningCertificate": "MIIEGDCCAwCgAwIBAgIJAOrYj9oLEJCwMA0GCSqGSIb3DQEBCwUAMGUxCzAJBgNVBAYTAklUMQ4wDAYDVQQIEwVJdGFseTENMAsGA1UEBxMEUm9tZTENMAsGA1UEChMEQWdJRDESMBAGA1UECxMJQWdJRCBURVNUMRQwEgYDVQQDEwthZ2lkLmdvdi5pdDAeFw0xOTA0MTExMDAyMDhaFw0yNTAzMDgxMDAyMDhaMGUxCzAJBgNVBAYTAklUMQ4wDAYDVQQIEwVJdGFseTENMAsGA1UEBxMEUm9tZTENMAsGA1UEChMEQWdJRDESMBAGA1UECxMJQWdJRCBURVNUMRQwEgYDVQQDEwthZ2lkLmdvdi5pdDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAK8kJVo+ugRrbbv9xhXCuVrqi4B7/MQzQc62ocwlFFujJNd4m1mXkUHFbgvwhRkQqo2DAmFeHiwCkJT3K1eeXIFhNFFroEzGPzONyekLpjNvmYIs1CFvirGOj0bkEiGaKEs+/umzGjxIhy5JQlqXE96y1+Izp2QhJimDK0/KNij8I1bzxseP0Ygc4SFveKS+7QO+PrLzWklEWGMs4DM5Zc3VRK7g4LWPWZhKdImC1rnS+/lEmHSvHisdVp/DJtbSrZwSYTRvTTz5IZDSq4kAzrDfpj16h7b3t3nFGc8UoY2Ro4tRZ3ahJ2r3b79yK6C5phY7CAANuW3gDdhVjiBNYs0CAwEAAaOByjCBxzAdBgNVHQ4EFgQU3/7kV2tbdFtphbSA4LH7+w8SkcwwgZcGA1UdIwSBjzCBjIAU3/7kV2tbdFtphbSA4LH7+w8SkcyhaaRnMGUxCzAJBgNVBAYTAklUMQ4wDAYDVQQIEwVJdGFseTENMAsGA1UEBxMEUm9tZTENMAsGA1UEChMEQWdJRDESMBAGA1UECxMJQWdJRCBURVNUMRQwEgYDVQQDEwthZ2lkLmdvdi5pdIIJAOrYj9oLEJCwMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAJNFqXg/V3aimJKUmUaqmQEEoSc3qvXFITvT5f5bKw9yk/NVhR6wndL+z/24h1OdRqs76blgH8k116qWNkkDtt0AlSjQOx5qvFYh1UviOjNdRI4WkYONSw+vuavcx+fB6O5JDHNmMhMySKTnmRqTkyhjrch7zaFIWUSV7hsBuxpqmrWDoLWdXbV3eFH3mINA5AoIY/m0bZtzZ7YNgiFWzxQgekpxd0vcTseMnCcXnsAlctdir0FoCZztxMuZjlBjwLTtM6Ry3/48LMM8Z+lw7NMciKLLTGQyU8XmKKSSOh0dGh5Lrlt5GxIIJkH81C0YimWebz8464QPL3RbLnTKg+c=",
                "OrganizationLogoUrl": "https://validator.spid.gov.it/img/idp-logo.png",
                "SingleSignOnServiceUrlPost": "https://localhost:8443/samlsso",
                "SingleSignOutServiceUrlPost": "https://localhost:8443/samlsso",
                "SingleSignOnServiceUrlRedirect": "https://localhost:8443/samlsso",
                "SingleSignOutServiceUrlRedirect": "https://localhost:8443/samlsso",
                "Type": "DevelopmentProvider"
            },
            {
                "EntityId": "https://localhost:8443/demo",
                "Name": "LocalDemoSpid",
                "OrganizationName": "DemoSpid",
                "OrganizationDisplayName": "DemoSpid",
                "X509SigningCertificate": "MIIEGDCCAwCgAwIBAgIJAOrYj9oLEJCwMA0GCSqGSIb3DQEBCwUAMGUxCzAJBgNVBAYTAklUMQ4wDAYDVQQIEwVJdGFseTENMAsGA1UEBxMEUm9tZTENMAsGA1UEChMEQWdJRDESMBAGA1UECxMJQWdJRCBURVNUMRQwEgYDVQQDEwthZ2lkLmdvdi5pdDAeFw0xOTA0MTExMDAyMDhaFw0yNTAzMDgxMDAyMDhaMGUxCzAJBgNVBAYTAklUMQ4wDAYDVQQIEwVJdGFseTENMAsGA1UEBxMEUm9tZTENMAsGA1UEChMEQWdJRDESMBAGA1UECxMJQWdJRCBURVNUMRQwEgYDVQQDEwthZ2lkLmdvdi5pdDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAK8kJVo+ugRrbbv9xhXCuVrqi4B7/MQzQc62ocwlFFujJNd4m1mXkUHFbgvwhRkQqo2DAmFeHiwCkJT3K1eeXIFhNFFroEzGPzONyekLpjNvmYIs1CFvirGOj0bkEiGaKEs+/umzGjxIhy5JQlqXE96y1+Izp2QhJimDK0/KNij8I1bzxseP0Ygc4SFveKS+7QO+PrLzWklEWGMs4DM5Zc3VRK7g4LWPWZhKdImC1rnS+/lEmHSvHisdVp/DJtbSrZwSYTRvTTz5IZDSq4kAzrDfpj16h7b3t3nFGc8UoY2Ro4tRZ3ahJ2r3b79yK6C5phY7CAANuW3gDdhVjiBNYs0CAwEAAaOByjCBxzAdBgNVHQ4EFgQU3/7kV2tbdFtphbSA4LH7+w8SkcwwgZcGA1UdIwSBjzCBjIAU3/7kV2tbdFtphbSA4LH7+w8SkcyhaaRnMGUxCzAJBgNVBAYTAklUMQ4wDAYDVQQIEwVJdGFseTENMAsGA1UEBxMEUm9tZTENMAsGA1UEChMEQWdJRDESMBAGA1UECxMJQWdJRCBURVNUMRQwEgYDVQQDEwthZ2lkLmdvdi5pdIIJAOrYj9oLEJCwMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAJNFqXg/V3aimJKUmUaqmQEEoSc3qvXFITvT5f5bKw9yk/NVhR6wndL+z/24h1OdRqs76blgH8k116qWNkkDtt0AlSjQOx5qvFYh1UviOjNdRI4WkYONSw+vuavcx+fB6O5JDHNmMhMySKTnmRqTkyhjrch7zaFIWUSV7hsBuxpqmrWDoLWdXbV3eFH3mINA5AoIY/m0bZtzZ7YNgiFWzxQgekpxd0vcTseMnCcXnsAlctdir0FoCZztxMuZjlBjwLTtM6Ry3/48LMM8Z+lw7NMciKLLTGQyU8XmKKSSOh0dGh5Lrlt5GxIIJkH81C0YimWebz8464QPL3RbLnTKg+c=",
                "OrganizationLogoUrl": "https://validator.spid.gov.it/img/idp-logo.png",
                "SingleSignOnServiceUrl": "https://localhost:8443/demo/samlsso",
                "SingleSignOutServiceUrl": "https://localhost:8443/demo/samlsso",
                "SingleSignOnServiceUrlRedirect": "https://localhost:8443/demo/samlsso",
                "SingleSignOutServiceUrlRedirect": "https://localhost:8443/demo/samlsso",
                "Type": "DevelopmentProvider"
            }
        ]
```

**Comment by RossiNIT** [comment]
Refuso dal vecchio json.
Grazie
