### ISSUE TITLE
ChallengeAsync: SpidException: Errore generico

### ISSUE THREAD

**Issue by mar-rossini** [italia/spid-aspnetcore#72]
Buonasera a tutti,

utilizzo la libreria da anni per l'autenticazione con SPID ma da qualche tempo non riesco più a completare il giro. L'architettura è con un client Angular e server Asp NET Core.

In particolare mi sono accorto che la Challange va in 500, sollevando questo errore:

```
SPID.AspNetCore.Authentication.Exceptions.SpidException: Errore generico. Prova ad autenticarti più tardi.
   at SPID.AspNetCore.Authentication.Saml.SamlHandler.GetAuthnRequest(String requestId, String entityId, String assertionConsumerServiceURL, Nullable`1 assertionConsumerServiceIndex, UInt16 attributeConsumingServiceIndex, X509Certificate2 certificate, Int32 securityLevel, RequestMethod requestMethod, IdentityProvider identityProvider)
   at SPID.AspNetCore.Authentication.SpidHandler.HandleChallengeAsync(AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.ChallengeAsync(AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.AuthenticationService.ChallengeAsync(HttpContext context, String scheme, AuthenticationProperties properties)
   at Microsoft.AspNetCore.Mvc.ChallengeResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at CIE.AspNetCore.Authentication.Extensions.CieSPMetadataMiddleware.Invoke(HttpContext context, IOptionsSnapshot`1 options, IServiceProvidersFactory serviceProvidersFactory)
   at SPID.AspNetCore.Authentication.Extensions.SpidSPMetadataMiddleware.Invoke(HttpContext context, IOptionsSnapshot`1 options, IServiceProvidersFactory serviceProvidersFactory)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

La chiamata di login è:

`return Challenge(new AuthenticationProperties { RedirectUri = redirectURL ?? "/" }, SpidDefaults.AuthenticationScheme);`

con idpname in queryString valorizzato con "Poste", "Sielte", etc (va in errore su tutti gli idp).

Mi sfugge qualcosa? Specifico che fino a qualche tempo fa questo stesso codice funzionava perfettamente.

Vi ringrazio in anticipo per il prezioso supporto, 
Marco

**Comment by danielegiallonardo** [comment]
Riesci a intercettare l'eccezione e vedere i dettagli della SpidException? oltre al messaggio dovresti trovare anche una Reason e un ErrorCode. Probabilmente dovresti riuscire a farlo dalla pagina di Errore.

**Comment by mar-rossini** [comment]
Ciao Daniele,

ti ringrazio intanto per la risposta. Temo di non essere riuscito a recuperare l'informazione che richiedi.

Ho attivato il LogHandler nella configurazione del servizio di Authentication, intercettato la catch nel contreller ed anche provato ad eseguire un check con SAML-tracer.

Ti viene in mente qualche punto di debug ulteriore?

La pagina di errore è quella generica di asp net, non vengo proprio re-indirizzato a quella dell'idp:

![image](https://github.com/italia/spid-aspnetcore/assets/149949193/eed13449-7930-48f6-ba2b-e590ddb4ca1f)

Grazie,
Marco

**Comment by mar-rossini** [comment]
Ciao a tutti,

sono riuscito a stampare l'errore e ho connesso i punti. Il problema era nel fatto che, utilizzando ancora la vecchia config avevo "SingleSignOnServiceUrl" nelle settings e non "SingleSignOnServiceUrlPost".

Magari potrebbe aver senso indicare come Obsolete la vecchia prop per quelli che ancora non utilizzano la get dal json online.

Grazie per il supporto,
Marco R.

**Comment by danielegiallonardo** [comment]
Ciao,
sono contento che tu abbia trovato il problema e risolto.
Occhio però che in documentazione è riportato: https://github.com/italia/spid-aspnetcore?tab=readme-ov-file#upgrade-dalla-versione-1x-alla-2x
Chiudo

**Comment by mar-rossini** [comment]
Buongiorno Daniele,

perdona ancora il disturbo, sono mortificato nello scrivere ancora ma purtroppo non mi sento così esperto e sono davvero in difficoltà. Temo di aver cantato vittoria troppo presto, ho superato lo step di Challenge correttamente. Ora gli idp mi rimandano alla pagina di consent e riesco a vedere i Cookie (Spid.Properties) correttamente valorizzati sul client. Non appena premo sul pulsante di "Acconsento" vengo re-indirizzato, dopo lo step di external-login, ad una pagina "/signin-spid" la quale va in errore:

![image](https://github.com/italia/spid-aspnetcore/assets/149949193/3c1be686-7111-4209-80e0-740fb2edf827)

Spulciando nei samples mi sono accorto che nel vostro caso effettuate una Callback alla redirectUrl quindi ho modificato la Challange che eseguivo da:

`return Challenge(new AuthenticationProperties { RedirectUri = redirectURL ?? "/" }, SpidDefaults.AuthenticationScheme);`

a

```
return Challenge(new AuthenticationProperties { RedirectUri = nameof(Callback) }, SpidDefaults.AuthenticationScheme);

[HttpGet]
public async Task<IActionResult> Callback()
{
    //Just for test
    return Redirect("/");
}
```

L'eccezione che ottengo lato Log è :

```
SPID.AspNetCore.Authentication.Exceptions.SpidException: Errore generico. Prova ad autenticarti più tardi.
at SPID.AspNetCore.Authentication.Helpers.BusinessValidation.ValidationCondition(Func`1 condition, SpidException error)
at SPID.AspNetCore.Authentication.Saml.SamlHandler.ValidateAuthnResponse(ResponseType response, AuthnRequestType request, IdentityProvider identityProvider, String serializedResponse)
at SPID.AspNetCore.Authentication.SpidHandler.ValidateAuthenticationResponse(ResponseType response, AuthnRequestType request, AuthenticationProperties properties, String idpName, String serializedResponse)
at SPID.AspNetCore.Authentication.SpidHandler.HandleRemoteAuthenticateAsync()
Error from RemoteAuthentication: Errore generico. Prova ad autenticarti più tardi..
HTTP POST /signin-spid responded 500 in 10.2220 ms <s:Serilog.AspNetCore.RequestLoggingMiddleware>
System.Exception: An error was encountered while handling the remote login.
SPID.AspNetCore.Authentication.Exceptions.SpidException: Errore generico. Prova ad autenticarti più tardi.
at SPID.AspNetCore.Authentication.Helpers.BusinessValidation.ValidationCondition(Func`1 condition, SpidException error)
at SPID.AspNetCore.Authentication.Saml.SamlHandler.ValidateAuthnResponse(ResponseType response, AuthnRequestType request, IdentityProvider identityProvider, String serializedResponse)
at SPID.AspNetCore.Authentication.SpidHandler.ValidateAuthenticationResponse(ResponseType response, AuthnRequestType request, AuthenticationProperties properties, String idpName, String serializedResponse)
at SPID.AspNetCore.Authentication.SpidHandler.HandleRemoteAuthenticateAsync()
--- End of inner exception stack trace ---
at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
```

ed infine la configurazione lato setting, con un esempio di provider, è la seguente:

```
"Spid": {
    "Providers": [
	...,
      {
        "Name": "Poste",
        "OrganizationName": "Poste Italiane SpA",
        "OrganizationDisplayName": "Poste Italiane SpA",
        "OrganizationUrlMetadata": "https://posteid.poste.it/jod-fs/metadata/metadata.xml",
        "OrganizationUrl": "https://www.poste.it/",
        "OrganizationLogoUrl": "https://raw.githubusercontent.com/italia/spid-sp-access-button/master/src/production/img/spid-idp-posteid.svg",
        "SingleSignOnServiceUrlPost": "https://posteid.poste.it/jod-fs/ssoservicepost",
        "SingleSignOutServiceUrlPost": "https://posteid.poste.it/jod-fs/sloservicepost",
        "Method": "Post",
        "Type": "IdentityProvider"
      },
	  ...
    ],
    "Certificate": ...,
    "IsLocalValidatorEnabled": false,
    "IsStagingValidatorEnabled": false,
    "EntityId": "https://www.my_site.it",
    "AssertionConsumerServiceURL": null,
    "AssertionConsumerServiceIndex": 0,
    "AttributeConsumingServiceIndex": 0,
    "RandomIdentityProvidersOrder": true
  }
```

Dove sto sbagliando?

Vi sono molto grato per tutto il lavoro che avete fatto e per il supporto.

Grazie,
Marco R.

**Comment by danielegiallonardo** [comment]
La redirect a /signin-spid è corretta, perchè è l'endpoint (di default, volendo è customizzabile) esposto dalla libreria per ricevere le response che provengono dal IdP. Successivamente è la libreria che, dopo aver effettuato tutte le verifiche sulla response, effettua la redirect alla RedirectUri specificata in fase di Challenge.
In questo caso l'errore avviene in fase di validazione della response, ma, come già detto in precedenza, bisognerebbe capire (magari impostando una ErrorPage e intercettando l'eccezione lì dentro) qual è la Reason e l'ErrorCode della SpidException che viene lanciata.
Puoi seguire la guida sul readme nella sezione dedicata per vedere come impostare una ErrorPage custom.

**Comment by mar-rossini** [comment]
Dunque, @danielegiallonardo ti ringrazio sempre per le pronte risposte.

Ho recuperato ErrorCode e Reason in particolare:

ErroCode: ResponseFirmaNonValida 
Reason: Signature non valida

Ho provato ad aggiungere la field X509SigningCertificate nelle settings ma non ha sortito alcun effetto.

Devo far ricaricare il metadata dai colleghi di Agid? O magari mi sfugge qualcosa di più semplice?

Grazie ancora,
Marco R.
