### ISSUE TITLE
Autenticazione SPID con Firefox, errore generico

### ISSUE THREAD

**Issue by PiemP** [italia/spid-aspnetcore#81]
Utilizzando Firefox ricevo un problema di autenticazione che riporta un messaggio di errore generico. Questo problema si verifica solo quando uso le istanze di produzione degli IdP e non quando uso il sistema tramite `spid-sp-test` o similari. 

La problematica credo derivi da questo controllo: 

https://github.com/italia/spid-aspnetcore/blob/d5d8d979cf4140e68362c3d8d47f947b335b926f/src/SPID.AspNetCore.Authentication/SpidHandler.cs#L762

Visto che nei log applicativi ho riscontrato il seguente stack trace: 

```
SPID.AspNetCore.Authentication.SpidHandler|Exception occurred while processing message. SPID.AspNetCore.Authentication.Exceptions.SpidException: Errore generico. Prova ad autenticarti più tardi.
   at SPID.AspNetCore.Authentication.Helpers.BusinessValidation.ValidationCondition(Func`1 condition, SpidException error) in ...spid-aspnetcore\src\SPID.AspNetCore.Authentication\Helpers\BusinessValidation.cs:line 20
   at SPID.AspNetCore.Authentication.AuthenticationPropertiesExtensions.Load(AuthenticationProperties properties, HttpRequest request, ISecureDataFormat`1 encryptor) in ...spid-aspnetcore\src\SPID.AspNetCore.Authentication\SpidHandler.cs:line 772
   at SPID.AspNetCore.Authentication.SpidHandler.HandleRemoteAuthenticateAsync() in ...spid-aspnetcore\src\SPID.AspNetCore.Authentication\SpidHandler.cs:line 165    at SPID.AspNetCore.Authentication.Helpers.BusinessValidation.ValidationCondition(Func`1 condition, SpidException error) in ...spid-aspnetcore\src\SPID.AspNetCore.Authentication\Helpers\BusinessValidation.cs:line 20
   at SPID.AspNetCore.Authentication.AuthenticationPropertiesExtensions.Load(AuthenticationProperties properties, HttpRequest request, ISecureDataFormat`1 encryptor) in ...spid-aspnetcore\src\SPID.AspNetCore.Authentication\SpidHandler.cs:line 772
   at SPID.AspNetCore.Authentication.SpidHandler.HandleRemoteAuthenticateAsync() in ...spid-aspnetcore\src\SPID.AspNetCore.Authentication\SpidHandler.cs:line 165
```

Qualcuno ha riscontrato il medesimo problema? La cosa divertente è che, se eseguo il browser in "private window" l'autenticazione funziona perfettamente.

Il problema si presenta solo con Firefox.

Grazie.

**Comment by PiemP** [comment]
niente... non mi sono accorto che il sito veniva aperto in http e non https.

😞
